export const GET_TOKEN_SUCCESSFUL = 'GET_TOKEN_SUCCESSFUL';
export const GET_TOKEN_PENDING = 'GET_TOKEN_PENDING';
export const GET_TOKEN_FAILURE = 'GET_TOKEN_FAILURE';
export const TOKEN_AUTH_FAILED = 'TOKEN_AUTH_FAILED';
